excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Newnew4.github.io
title: Be The Animal Farmer
tagline: We're trying to impart knowledge to livestock and pet breeders.
description: My awesome new site
paginate: 5